### ISSUE TITLE
Add responsive layout recalculation

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-dashboard#8]

**Comment by apechenko-sc** [comment]
Please, implement. We are waiting for it [here](https://github.com/OpusCapita/invoice/issues/101)

**Comment by kvolkovich-sc** [comment]
Done. API has been changed. See [demo](https://opuscapita.github.io/react-dashboard/?currentComponentId=%40opuscapita%2Freact-dashboard%2F0.0.4%2FDashboard&currentComponentName=Dashboard&maxContainerWidth=100%25&showSidebar=true).
